# Common defaults for all services
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,metrics,env,configprops
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true
    env:
      enabled: true
    configprops:
      enabled: true

logging:
  level:
    org.springframework.cloud: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

# Feature flags
features:
  enable-detailed-logging: false
  enable-metrics: true
  enable-tracing: false