spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456!
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: employee
    open-in-view: false
  flyway:
    locations: classpath:/db/migration
    schemas: employee
    default-schema: employee
    table: flyway_schema_history_employees
    create-schemas: true
    baseline-version: 0
    validate-migration-naming: true

server:
  port: 8081

# Employee service specific logging
logging:
  level:
    com.example.employee: DEBUG
    org.springframework.web: INFO

# Feature flags specific to employee service
features:
  enable-department-enrichment: true
  enable-employee-validation: true