spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456!
    schema: project
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: project
  flyway:
    enabled: true
    schemas: project
    locations: classpath:db/migration
    table: flyway_schema_history_project

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, env, configprops, metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.example.project: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG

# Feature flags for project service
features:
  enable-employee-validation: true
  enable-project-audit: true
  enable-member-enrichment: true
  enable-bulk-operations: true

# OpenFeign configuration
feign:
  client:
    config:
      EMPLOYEE-SERVICE:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
  circuitbreaker:
    enabled: true